$(document).ready(function(){
	var prof = sessionStorage.getItem('prof');
	var nwprof = sessionStorage.getItem('nwprof');
	var spells = sessionStorage.getItem('spells');
	var name = sessionStorage.getItem('name');
	var str = sessionStorage.getItem('str');
	var dex = sessionStorage.getItem('dex');
	var int = sessionStorage.getItem('int');
	var wis = sessionStorage.getItem('wis');
	var con = sessionStorage.getItem('con');
	var cha = sessionStorage.getItem('cha');
	var race = sessionStorage.getItem('race');
	var charClass = sessionStorage.getItem('class');
	var bio = sessionStorage.getItem('bio');
	var age = sessionStorage.getItem('age');
	var height = sessionStorage.getItem('height');
	var weight = sessionStorage.getItem('weight');
	var hp = sessionStorage.getItem('hp');
	//var items = sessionStorage.getItem('itemss');
	$("#prof").append(prof);
	$("#nwprof").append(nwprof);
	$("#spells").append(spells);
	$("#name").append(name);
	$("#hp").append(hp);
	$("#age").append(age);
	$("#height").append(height);
	$("#weight").append(weight);
	$("#bio").append(bio);
	$("#str").append(str);
	$("#dex").append(dex);
	$("#int").append(int);
	$("#wis").append(wis);
	$("#con").append(con);
	$("#cha").append(cha);
	$("#race").append(race);
	$("#class").append(charClass);
	//$("#listitems").append(items);
	$("#printchar").click(function() {
		window.print();
	});
});